// <auto-generated />
using System;
using FitnessClubEvolution.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FitnessClubEvolution.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FitnessClubEvolution.Api.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCliente"));

                    b.Property<bool>("AceptaWhatsApp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("FechaBajaWhatsApp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaConsentimientoWhatsApp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdRutina")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdCliente");

                    b.HasIndex("Documento");

                    b.HasIndex("IdRutina");

                    b.HasIndex("Telefono");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("FitnessClubEvolution.Api.Models.Cuota", b =>
                {
                    b.Property<int>("IdCuota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCuota"));

                    b.Property<string>("EstadoPago")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Confirmado");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("FechaVencimiento")
                        .HasColumnType("date");

                    b.Property<int>("IdCliente")
                        .HasColumnType("integer");

                    b.Property<int?>("IdEntrenador")
                        .HasColumnType("integer");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Monto")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.HasKey("IdCuota");

                    b.HasIndex("IdEntrenador");

                    b.HasIndex("IdCliente", "FechaVencimiento");

                    b.ToTable("Cuotas");
                });

            modelBuilder.Entity("FitnessClubEvolution.Api.Models.Ejercicio", b =>
                {
                    b.Property<int>("IdEjercicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEjercicio"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<int?>("DuracionVideoSegundos")
                        .HasColumnType("integer");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("FotoOVideo")
                        .HasColumnType("text");

                    b.Property<string>("GrupoMuscular")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Sin clasificar");

                    b.Property<byte[]>("ImagenPreview")
                        .HasColumnType("bytea");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreArchivoImagen")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("NombreArchivoVideo")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long?>("TamanoImagenBytes")
                        .HasColumnType("bigint");

                    b.Property<long?>("TamanoVideoBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoContenidoImagen")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TipoContenidoVideo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<byte[]>("VideoTutorial")
                        .HasColumnType("bytea");

                    b.HasKey("IdEjercicio");

                    b.HasIndex("GrupoMuscular", "Estado");

                    b.HasIndex("Nombre");

                    b.ToTable("Ejercicios");
                });

            modelBuilder.Entity("FitnessClubEvolution.Api.Models.Entrenador", b =>
                {
                    b.Property<int>("IdEntrenador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEntrenador"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Contrasena")
                        .HasColumnType("text");

                    b.Property<string>("ContrasenaHash")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("NombreUsuarioNormalizado")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Administrador");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IdEntrenador");

                    b.HasIndex("NombreUsuarioNormalizado")
                        .IsUnique();

                    b.HasIndex("Telefono");

                    b.ToTable("Entrenadores");
                });

            modelBuilder.Entity("FitnessClubEvolution.Api.Models.MensajeWhatsapp", b =>
                {
                    b.Property<long>("IdMensajeWhatsapp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdMensajeWhatsapp"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("EstadoProcesamiento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("FechaProcesamiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaRecepcion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("IdCliente")
                        .HasColumnType("integer");

                    b.Property<string>("IdMensajeMeta")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("Intentos")
                        .HasColumnType("integer");

                    b.Property<string>("Resumen")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("UltimoError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("IdMensajeWhatsapp");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdMensajeMeta")
                        .IsUnique();

                    b.HasIndex("Telefono", "FechaRecepcion");

                    b.ToTable("MensajesWhatsapp");
                });

            modelBuilder.Entity("FitnessClubEvolution.Api.Models.Notificacion", b =>
                {
                    b.Property<int>("IdNotificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdNotificacion"));

                    b.Property<string>("Canal")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("WhatsApp");

                    b.Property<string>("ClaveIdempotencia")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Pendiente");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaEnvio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaLectura")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaProgramada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdCliente")
                        .HasColumnType("integer");

                    b.Property<string>("IdMensajeExterno")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("Intentos")
                        .HasColumnType("integer");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Referencia")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UltimoError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("IdNotificacion");

                    b.HasIndex("ClaveIdempotencia")
                        .IsUnique();

                    b.HasIndex("IdCliente");

                    b.HasIndex("Estado", "FechaProgramada");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("FitnessClubEvolution.Api.Models.Rutina", b =>
                {
                    b.Property<int>("IdRutina")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRutina"));

                    b.Property<int?>("CantidadPaginas")
                        .HasColumnType("integer");

                    b.Property<byte[]>("ContenidoPdf")
                        .HasColumnType("bytea");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("FechaCarga")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NombreArchivoPdf")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long?>("TamanoBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoContenidoPdf")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdRutina");

                    b.HasIndex("Nombre");

                    b.ToTable("Rutinas");
                });

            modelBuilder.Entity("FitnessClubEvolution.Api.Models.Servicio", b =>
                {
                    b.Property<int>("IdServicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdServicio"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Duracion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<byte[]>("Imagen")
                        .HasColumnType("bytea");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("NombreArchivoImagen")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("Precio")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("TipoContenidoImagen")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("IdServicio");

                    b.HasIndex("Nombre");

                    b.ToTable("Servicios");
                });

            modelBuilder.Entity("FitnessClubEvolution.Api.Models.SolicitudRecuperacion", b =>
                {
                    b.Property<long>("IdSolicitudRecuperacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdSolicitudRecuperacion"));

                    b.Property<string>("CodigoHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pendiente");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaUso")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdEntrenador")
                        .HasColumnType("integer");

                    b.Property<int>("Intentos")
                        .HasColumnType("integer");

                    b.Property<string>("IpSolicitud")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("MaxIntentos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5);

                    b.HasKey("IdSolicitudRecuperacion");

                    b.HasIndex("IdEntrenador", "Estado", "FechaExpiracion");

                    b.ToTable("SolicitudesRecuperacion");
                });

            modelBuilder.Entity("FitnessClubEvolution.Api.Models.Cliente", b =>
                {
                    b.HasOne("FitnessClubEvolution.Api.Models.Rutina", "Rutina")
                        .WithMany("Clientes")
                        .HasForeignKey("IdRutina")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rutina");
                });

            modelBuilder.Entity("FitnessClubEvolution.Api.Models.Cuota", b =>
                {
                    b.HasOne("FitnessClubEvolution.Api.Models.Cliente", "Cliente")
                        .WithMany("Cuotas")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitnessClubEvolution.Api.Models.Entrenador", "Entrenador")
                        .WithMany("CuotasRegistradas")
                        .HasForeignKey("IdEntrenador")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cliente");

                    b.Navigation("Entrenador");
                });

            modelBuilder.Entity("FitnessClubEvolution.Api.Models.MensajeWhatsapp", b =>
                {
                    b.HasOne("FitnessClubEvolution.Api.Models.Cliente", "Cliente")
                        .WithMany("MensajesWhatsapp")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("FitnessClubEvolution.Api.Models.Notificacion", b =>
                {
                    b.HasOne("FitnessClubEvolution.Api.Models.Cliente", "Cliente")
                        .WithMany("Notificaciones")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("FitnessClubEvolution.Api.Models.SolicitudRecuperacion", b =>
                {
                    b.HasOne("FitnessClubEvolution.Api.Models.Entrenador", "Entrenador")
                        .WithMany("SolicitudesRecuperacion")
                        .HasForeignKey("IdEntrenador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entrenador");
                });

            modelBuilder.Entity("FitnessClubEvolution.Api.Models.Cliente", b =>
                {
                    b.Navigation("Cuotas");

                    b.Navigation("MensajesWhatsapp");

                    b.Navigation("Notificaciones");
                });

            modelBuilder.Entity("FitnessClubEvolution.Api.Models.Entrenador", b =>
                {
                    b.Navigation("CuotasRegistradas");

                    b.Navigation("SolicitudesRecuperacion");
                });

            modelBuilder.Entity("FitnessClubEvolution.Api.Models.Rutina", b =>
                {
                    b.Navigation("Clientes");
                });
#pragma warning restore 612, 618
        }
    }
}
